<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Modern.Forms">
        <HintPath>..\..\..\..\.nuget\packages\modern.forms\0.3.0\lib\net6.0\Modern.Forms.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rayman2Lib\Rayman2Lib.csproj" />
    </ItemGroup>

</Project>
