<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Modern.Forms" Version="0.3.0" />
      <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
      <PackageReference Include="System.Resources.Extensions" Version="10.0.12" />
      <PackageReference Include="System.Windows.Extensions" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="bin\Release\net10.0\Rayman2Lib.deps.json" />
      <Content Include="bin\Release\net10.0\Rayman2Lib.dll" />
      <Content Include="bin\Release\net10.0\Rayman2Lib.pdb" />
      <Content Include="bin\Release\Rayman2Lib.1.0.0.nupkg" />
    </ItemGroup>

</Project>
